import "../styles/tailwind.css";
import "../styles/globals.css";
import { suisseIntl } from "./fonts";
import { ReactLenis } from "@/lib/lenis";
import type { Metadata } from "next";
import Wrapper from "@/layouts/Wrapper";

export const metadata: Metadata = {
  title: "Krea AI - Cartolinks Solution LTD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReactLenis
        root
        options={{
          lerp: 0.05,
        }}
      >
        <body
          className={`${suisseIntl.className} antialiased bg-white dark:bg-black`}
          suppressHydrationWarning
        >
          <Wrapper>{children}</Wrapper>
        </body>
      </ReactLenis>
    </html>
  );
}
